name: Deploy Angular to Staging (Manual)

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Rama a desplegar en Staging'
                required: true
                type: string
                default: 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout de la rama seleccionada
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}
                  fetch-depth: 0  # Mejora: Clona todo el historial de Git

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'  # Habilita cache de npm

            - name: Cache Node Modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

            - name: Instalar dependencias
              run: |
                  npm ci --prefer-offline  # Usa el cache si está disponible

            - name: Build para Staging
              run: |
                  npm install -g @angular/cli@latest  # Asegura la versión correcta de Angular CLI
                  npm run build -- --configuration=staging

            - name: Verificar archivos construidos
              run: ls -la ./dist/sakai-ng  # Debug: Confirma que los archivos existen

            - name: Desplegar a Staging via SFTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4  # Versión explícita (última estable)
              with:
                  server: ${{ secrets.STAGING_FTP_SERVER }}
                  username: ${{ secrets.STAGING_FTP_USERNAME }}
                  password: ${{ secrets.STAGING_FTP_PASSWORD }}
                  local-dir: ./dist/sakai-ng/
                  remote-dir: /home/staging/portal-frontend/
                  dangerous-clean-slate: true
                  git-sftp-args: '-o ConnectTimeout=60'  # Aumenta tiempo de conexión
